### ISSUE TITLE
How to use env variables to set the orm config dsn value - "modules.orm.dsn"

### ISSUE THREAD

**Issue by singh-jay** [ankorstore/yokai#216]
Thanks for this amazing template, 
I want to use the DATABASE_URL env variable as the orm dsn value, how can I use this env variable inside config.yaml. I can't find any solutions in the docs. 
Please help me.

**Comment by ekkinox** [comment]
This can be done via [env var placeholders](https://ankorstore.github.io/yokai/modules/fxconfig/#env-var-placeholders).

You just need to do:

`modules.orm.dsn: ${DATABASE_URL}`

**Comment by ekkinox** [comment]
Let me know if this answers your question @singh-jay , so I can close the issue.

For information, a `database/sql` based Yokai module will be released soon, if you don't want to work with an ORM but with pure SQL or tools like [SQLC](https://sqlc.dev/).

Thanks :+1:

**Comment by singh-jay** [comment]
@ekkinox Thanks for the quick reply. 
it's working fine now.

Please close the issue.
