### ISSUE TITLE
middleware & gorm.DB

### ISSUE THREAD

**Issue by mak-alex** [ankorstore/yokai#218]
Hi. Tell me how to add the gorm.DB in middleware?

a basic example would not hurt, I did not find it in the documentation

P.S. I'm sorry for my English))

**Comment by ekkinox** [comment]
It's actually documented (with another dependency example), you can check the doc [here](https://ankorstore.github.io/yokai/modules/fxhttpserver/#middlewares-registration).

For your case:

First create the middleware that injects the `*gorm.DB`, for example:

```go
package middleware

import (
    "github.com/labstack/echo/v4"
    "gorm.io/gorm"
)

type ExampleMiddleware struct {
    db *gorm.DB
}

func NewExampleMiddleware(db *gorm.DB) *ExampleMiddleware {
    return &ExampleMiddleware{
        db: db,
    }
}

func (m *ExampleMiddleware) Handle() echo.MiddlewareFunc {
    return func(next echo.HandlerFunc) echo.HandlerFunc {
        return func(c echo.Context) error {
            // you can use m.db here

            return next(c)
        }
    }
}
```

Then, register you middleware in `internal/router.go`:

```go
...
fxhttpserver.AsMiddleware(middleware.NewExampleMiddleware, fxhttpserver.GlobalUse),
...
```

Using `fxhttpserver.AsMiddleware()` will autowire your middleware constructor, and therefore inject the `*gorm.DB`.

Let me know if this soved your issue :+1:

**Comment by mak-alex** [comment]
Yes, thanks, the example in the documentation works. My question is how to use for certain endpoints
```go
fxhttpserver.AsHandlersGroup(
   "/api/auth", 
   []*fxhttpserver.HandlerRegistration{
	fxhttpserver.NewHandlerRegistration("POST", "/register", handler.NewRegisterHandler),
	fxhttpserver.NewHandlerRegistration("POST", "/login", handler.NewAuthLoginHandler, middleware.CustomAuthMIddleware), // here
```

**Comment by mak-alex** [comment]
Sorry if the question is stupid, unfortunately, I don't quite understand how to solve it yet)

**Comment by ekkinox** [comment]
No pb! 

There is 3 ways to register middlewares:

- globally with `fxhttpserver.AsMiddleware()` => will apply for all handlers
- for a specific handler with `fxhttpserver.AsHandler()` where you can pass several middlewares => will apply only for this handler
- for a specific handler group with `fxhttpserver.AsHandlersGroup()` where you can pass several middlewares => will apply only for the handlers of this group

See [usage](https://ankorstore.github.io/yokai/modules/fxhttpserver/#usage).

**Comment by mak-alex** [comment]
Thank you so much for the feedback, now it's clear. I wish the project good development and success in all its endeavors

**Comment by ekkinox** [comment]
Thanks a lot, appreciated.

Closing the issue.
