### ISSUE TITLE
How to redirect to handler function instead of default Handle function of the handler

### ISSUE THREAD

**Issue by templatedop** [ankorstore/yokai#279]
Hi,
Firstly thank you for the template.
Learnt a lot.

If I am using yokai template,..  handler intialised in router redirects to default handle function.

`fxhttpserver.AsHandler("GET", "/example", handler.NewExampleHandler, middleware.NewExampleMiddleware, echomiddleware.CORS()),`

I would like to redirect to a function in handler instead of default handle function.
My present project already implemented in that way.
The project is spread across 30 teams.
As such cannot change it.

I am unable to shift to yokai template because of this.

Presently  constructor handlers are getting initialised   in a separate module
And then in routes it is getting redirected to concerned function of the handler.
How to achieve this in yokai template.

Can you please guide.

**Comment by ekkinox** [comment]
The idea of Yokai http handlers is for them to handle only one route, injecting only what they need for this route.

If you have a big handler with many dependencies, with several funcs for several routes, I suggest splitting it into dedicated handlers (1 per route), you'll also significantly increase testability/modularity this way.

**Comment by templatedop** [comment]
I understand.
As informed it is not easier to implement this in existing project.
Would like to utilise yokai without per route for the present as existing project cannot be changed 
Can you please hint /guide me to use http server to route handler function .

Kindly help...

**Comment by ekkinox** [comment]
If you really can't split your big handler, you can still register handler funcs in Yokai that would call the functions from it:

```
fxhttpserver.AsHandler("GET", "/something", func(c echo.Context) error {
  yourHandler.Something() // call your handler

  return c.JSON(http.StatusOK, "ok")
}),
```

But the main interest to split it would be to take benefits of the automatic dependency injection.

**Comment by templatedop** [comment]
Hey!
Thank you. Will try and update you.
