### ISSUE TITLE
Wildcard Route Not Working in Yokai with fxhttpserver

### ISSUE THREAD

**Issue by mak-alex** [ankorstore/yokai#292]
Hello! I’m encountering an issue with using a wildcard route in Yokai with fxhttpserver. When setting up a route with /:service/*, I get a 404 Not Found error. My expectation is that this route should proxy all requests matching the pattern /:service/* (e.g., /hello_world/test), but it doesn’t seem to work as expected.

**Details:**

- Yokai Version: v1.5.0

- Routing Code:
```go
func Router() fx.Option {
    return fx.Options(
        fxhttpserver.AsMiddleware(fxapigateway.NewAuthenticationMiddleware, fxhttpserver.GlobalUse),
        fxhttpserver.AsHandler("ANY", "/:service/*", fxapigateway.NewProxyRequestHandler),
    )
}
```
- **Issue:** When calling any route, such as /hello_world/test, the server returns 404 Not Found.

**Steps to Reproduce:**

1. Added a route using `fxhttpserver.AsHandler("ANY", "/:service/*", fxapigateway.NewProxyRequestHandler)`.
2. Tried sending a `GET` request to `/hello_world/test`.

**What I’ve Tried:**
- Used various route patterns like `/:service/*` and `/:service/*/`.
- Verified that configuration is loading correctly and services are registered.
- Confirmed that requests reach the router, but the wildcard does not function as expected.

**Question:**
Is there a way to use a wildcard route `/:service/*` with `fxhttpserver` in Yokai, or is there something I might be missing in the configuration?

Thank you!

**Comment by ekkinox** [comment]
Hello :wave: 

Yokai httpserver module is built on top of [Echo](https://echo.labstack.com/docs/routing).

Echo, and therefore Yokai, are implementing the HTTP specs, so the (invalid) HTTP method `ANY` is not supported, it leads to a `405 Method Not Allowed` is you try to set this up.

You can use the [following valid methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods): `GET`, `HEAD`, `POST`, `PUT`, `PATCH`, `DELETE`, `CONNECT`, `OPTIONS`, `TRACE`, with in addition `PROPFIND` and `REPORT`.

I think you were maybe mislead by the fact Echo offers the func [Any()](https://pkg.go.dev/github.com/labstack/echo/v4#Echo.Any), that's not something Yokai offers today but I can add it in a next release if you really need to, let me know.

---

Now, about your routing issue, you have 2 solutions:

- with a wildcard

you can define an handler like this:

```go
func (h *ExampleHandler) Handle() echo.HandlerFunc {
	return func(c echo.Context) error {
		return c.String(http.StatusOK, fmt.Sprintf("Welcome to %s", c.Param("service")))
	}
}
```

and in the routing config:

```go
func Router() fx.Option {
	return fx.Options(
		fxhttpserver.AsHandler("GET", "/:service/*", handler.NewExampleHandler),
	)
}
```

this allows you to call `[GET] /hello_world/foo`:

![image](https://github.com/user-attachments/assets/4548ca78-bef7-4afa-a40c-1dbd8eb09fce)

 or even `[GET] /bye_world/bar`:

![image](https://github.com/user-attachments/assets/b4659c51-2db9-41da-b8cd-44c308622f70)

- with a 2nd path param

if you need to capture the second part of the URI, you can combine 2 path params.

you can define an handler like this:

```go
func (h *ExampleHandler) Handle() echo.HandlerFunc {
	return func(c echo.Context) error {
		return c.String(http.StatusOK, fmt.Sprintf("Service %q, name %q", c.Param("service"), c.Param("name")))
	}
}
```

and in the routing config:

```go
func Router() fx.Option {
	return fx.Options(
		fxhttpserver.AsHandler("GET", "/:service/:name", handler.NewExampleHandler),
	)
}
```


this allows you to call `[GET] /hello_world/foo`:

![image](https://github.com/user-attachments/assets/1cfe4501-be30-42aa-8cdd-cb3a1d504154)

 or even `[GET] /bye_world/bar`:

![image](https://github.com/user-attachments/assets/ecef2955-1b9a-4ab2-80c1-36dd99338be3)


Hope this helps :+1:

**Comment by mak-alex** [comment]
Thank you, @ekkinox, for the detailed and helpful response! I appreciate the explanation regarding the valid HTTP methods and the alternatives you provided for handling routing with wildcards.

Indeed, `Any()` would be ideal in this case, as it would allow us to streamline the handling of different HTTP methods within a single route. Our use case involves proxying requests to different microservices, so having `Any()` support would be invaluable for simplifying the routing setup.

If adding `Any()` is feasible in a future release, it would be a great addition to Yokai’s flexibility. Thanks again for your assistance!
