### ISSUE TITLE
Allow registration of an HTTP handler for multiple HTTP methods 

### ISSUE THREAD

**Issue by ekkinox** [ankorstore/yokai#293]
Allow the possibility to register an HTTP handler for more than one method.

Something like `AsHandler("GET,POST", ...) ` or even `AsHandler("*", ...) `.

See need expressed in https://github.com/ankorstore/yokai/issues/292.

Ping @mak-alex for follow up.

**Comment by mak-alex** [comment]
@ekkinox, thank you for the feedback and for your continuous dedication to making `Yokai` even better!

Using `*` as an option feels like the most logical and concise approach, particularly for users familiar with `Unix` conventions. This would simplify the registration of handlers for all `HTTP` methods while keeping the code both readable and compact. We suggest implementing support for `*` as a universal indicator for all methods, allowing for a cleaner and more intuitive way to manage `HTTP` method handling.

Thanks again for your vision and leadership in developing `Yokai`!

**Comment by ekkinox** [comment]
We can support all this:

- `AsHandler("GET", ...)` => only for GET
- `AsHandler("GET,POST", ...)` => only for GET and POST
`AsHandler("*", ...)` => for all methods 

Wdyt?

**Comment by mak-alex** [comment]
Hmm, I'm not entirely sure that listing multiple methods for a single handler is often needed. However, if the implementation is straightforward, it could certainly add some flexibility - why not? 🙂

For now, I’ve handled it like this:
```go
fxhttpserver.AsHandler("GET", "service/:serviceName/*", NewProxyRequestHandler),
fxhttpserver.AsHandler("POST", "service/:serviceName/*", NewProxyRequestHandler),
fxhttpserver.AsHandler("OPTIONS", "service/:serviceName/*", NewProxyRequestHandler),
fxhttpserver.AsHandler("DELETE", "service/:serviceName/*", NewProxyRequestHandler),
fxhttpserver.AsHandler("PUT", "service/:serviceName/*", NewProxyRequestHandler),
fxhttpserver.AsHandler("PATCH", "service/:serviceName/*", NewProxyRequestHandler),
```

Not the most elegant solution, but it works.

**Comment by ekkinox** [comment]
It works but you put several times in Yokai DI container the same handler, and calling multiple times the constructor, which is sub optimal.

I'll work on this feature asap and will ping you when it's ready 👍

**Comment by ekkinox** [comment]
@mak-alex I just released [fxhttpserver v1.6.0](https://github.com/ankorstore/yokai/releases/tag/fxhttpserver%2Fv1.6.0).

You can now use (on top of regular usage):

- a list of methods

for example, with

```go
fxhttpserver.AsHandler("GET,POST,DELETE", "/", handler.NewDashboardHandler),
```

the handler is registered for `GET`, `POST` and `DELETE`: 

![image](https://github.com/user-attachments/assets/0a0f95a8-5548-4c3f-afe6-0c962a2b5b35)

- a wildcard (`*`)

for example, with

```go
fxhttpserver.AsHandler("*", "/", handler.NewDashboardHandler),
```
the handler is registered for all HTTP methods supported by Echo: 

![image](https://github.com/user-attachments/assets/1b5a3d85-2dab-4b2e-a5fe-0593a8959fc0)

All this works in handlers groups registration as well.

I let you install [1.6.0](https://github.com/ankorstore/yokai/releases/tag/fxhttpserver%2Fv1.6.0), test and let me know if this works for you.

You can also check the [updated documentation](https://ankorstore.github.io/yokai/modules/fxhttpserver/#handlers-registration).

**Comment by mak-alex** [comment]
Ooooo yes, this is awesome! 🤩 I updated my code right away, and it’s working so elegantly now — thank you! 
<img width="888" alt="image" src="https://github.com/user-attachments/assets/e51d9ca5-caf8-4563-a04a-bbb855a414dc">

I’m genuinely impressed with how quickly you implemented this fix; that’s some top-notch project support! 🚀 

Thanks so much for the update and the new features. I’ll give [1.6.0](https://github.com/ankorstore/yokai/releases/tag/fxhttpserver/v1.6.0) a test with the wildcard and multi-method handler setup — it’s fantastic to see `Yokai` becoming even more flexible. I’ll dive into the new docs as well. 📚 

I hope the project keeps expanding with more modules, like `Kafka`, `config` integration with `Vault`, `S3/Minio`, `Service Discovery and Load Balancing (with Kubernetes, Consul or Etcd)` and other awesome features! It would also be amazing to have support for multiple `ORM` connections since there are scenarios where that’s needed. Built-in support for dbresolver and sharding in `ORM` would take things to the next level too. 🙌

Wishing you all the best with everything you’re working on! 🚀

**Comment by mak-alex** [comment]
Oh yes, if these extensions make their way into `Yokai`, it won't just be cool—it'll be unstoppable! 😎🚀

Imagine `Yokai` with built-in `Kafka`, seamless `Vault` integration, advanced `ORM` capabilities with multi-DB support, `sharding`, `caching`, and more! With all these features, it'll be ready to handle anything thrown at it, from high-load distributed systems to complex microservices architectures. Adding customizable authentication (maybe `OAuth2` with `OpenID`) and service discovery would make it a go-to framework for any serious backend project.

And hey, a notification module like `fxnotify` with support for `email`, `WhatsApp`, `Telegram`, and more channels would be amazing too! 💌📲 

Yokai will truly be a force to be reckoned with! 💪

Looking forward to seeing this powerhouse evolve. `Yokai` FTW! 🎉

**Comment by ekkinox** [comment]
Hey @mak-alex  :wave: 

I just released [fxhttpserver 1.6.1](https://github.com/ankorstore/yokai/releases/tag/fxhttpserver%2Fv1.6.1), cause in the screenshot you made, we don't see what is the actual HTTP method used when we register with `*`.

Now looks like this:

![image](https://github.com/user-attachments/assets/20009539-c962-4e9b-a70a-441620b4fdb6)

Feel free to update to [1.6.1](https://github.com/ankorstore/yokai/releases/tag/fxhttpserver%2Fv1.6.1).

**Comment by mak-alex** [comment]
<img width="935" alt="image" src="https://github.com/user-attachments/assets/729a3f1c-2921-4704-98c2-ae4090558a31">
Hey! 👋

Just pulled the update, and yep, everything’s looking spot on now. Awesome work as always—thanks for the quick fix! 🚀😊

**Comment by ekkinox** [comment]
Also, many thanks for the kind words !

Replying to your suggestions:

> I hope the project keeps expanding with more modules, like Kafka, config integration with Vault, S3/Minio, Service Discovery and Load Balancing (with Kubernetes, Consul or Etcd) and other awesome features

For the Yokai extensions, there is a [yokai-contrib](https://github.com/ankorstore/yokai-contrib) repository:

- we'll put there all the libraries / instrumentation that are extending Yokai core features (like for example s3, kafka, elastic, etc)
- anyone can create a contrib module if they feel it's worth sharing with others
- contrib module would respect though the same general idea, i.e offering out of the box observability (logs, traces, metrics if relevant) and testability (like we did for example for the gcppubsub module)

> It would also be amazing to have support for multiple ORM connections since there are scenarios where that’s needed. Built-in support for dbresolver and sharding in ORM would take things to the next level too.

That's a good idea :+1:  Can I ask you to open an issue for this ? I'll try to check this at some point.

But as a side remark, even if Yokai offers an ORM module (gorm), but I strongly suggest to use the [SQL module](https://ankorstore.github.io/yokai/modules/fxsql/) instead: ORM are great until they're not. When project complexity grows, they very often become an obstacle. Since the SQL module offers the same level of automatic observability (logs, traces) than the ORM, since it offers also DB migrations and seeding mechanisms, and since you can combine it with excellent tooling like [SQLC](https://docs.sqlc.dev/en/latest/index.html), I suggest you take a look and consider the switch.

> And hey, a notification module like fxnotify with support for email, WhatsApp, Telegram, and more channels would be amazing too!

That's another good idea, and a good candidate for a contrib module as well :+1: 

---

If everything is OK regarding this current issue, I let you close it.

Have a great day :+1:

**Comment by mak-alex** [comment]
Hopefully, someday I'll find the time to join in and contribute into [yokai-contrib](https://github.com/ankorstore/yokai-contrib) 🙌 Right now, time is tight, but it would be amazing to jump in down the road!

Yeap, this issue seems resolved—thanks again for the feedback and the quick response! If everything looks good, let’s go ahead and close it.

Have a great day 👍
